name: native_libraries_in_flutter_using_dart_ffi
description: An example on How to access native libraries in Flutter using Dart FFI by Majid Hajian

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=2.14.0 <3.0.0'

dependencies:
  ffi: ^1.1.2
  ffigen: ^4.1.2
  path: ^1.8.1

ffigen:
  name: 'MathUtilsFFI'
  description: 'Written for the FFI article'
  output: 'lib/ffi/generated_bindings.dart'
  headers:
    entry-points:
      - 'native/math.h'
