name: native_libraries_in_flutter_using_dart_ffi
description: An example on How to access native libraries in Flutter using Dart FFI by Majid Hajian

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.15.1 <3.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  ffigen: ^4.1.2
  ffi: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/example.json

ffigen:
  output: 'lib/ffi/cjson_generated_bindings.dart'
  name: 'CJson'
  description: 'Holds bindings to cJSON.'
  headers:
    entry-points:
      - '../dart/native/cJSON/cJSON.h'
    include-directives:
      - '**cJSON.h'
  comments: false
  typedef-map:
    'size_t': 'IntPtr'
